apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          limits:
            memory: 128Mi
            cpu: 50m
          requests:
            cpu: 10m
            memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  template:
    spec:
      containers:
      - name: rabbitmq
        resources:
          limits:
            memory: 256Mi
            cpu: 100m
          requests:
            cpu: 50m
            memory: 128Mi 