apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: redis
        resources:
          limits:
            memory: 512Mi
            cpu: 200m
          requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: rabbitmq
        resources:
          limits:
            memory: 1Gi
            cpu: 500m
          requests:
            cpu: 200m
            memory: 512Mi 