apiVersion: v1
kind: ServiceAccount
metadata:
  name: semanix-backend-accessmanagement
  namespace: semanix
  labels:
    app.kubernetes.io/name: accessmanagement
    app.kubernetes.io/instance: semanix-backend
    
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: semanix-backend-requestmanagement
  namespace: semanix
  labels:
    app.kubernetes.io/name: requestmanagement
    app.kubernetes.io/instance: semanix-backend