apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semanix-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/devops_practice.git
    targetRevision: HEAD
    path: helm/charts
  destination:
    server: https://kubernetes.default.svc
    namespace: semanix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 