apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: redis
        resources:
          limits:
            memory: 256Mi
            cpu: 100m
          requests:
            cpu: 50m
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: rabbitmq
        resources:
          limits:
            memory: 512Mi
            cpu: 250m
          requests:
            cpu: 100m
            memory: 256Mi 