apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semanix-backend-accessmanagement
  namespace: argocd
spec:
  project: default
  source:
    repoURL: samthedonz.azurecr.io/helm
    targetRevision: 0.1.1
    chart: accessmanagement
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: serviceAccount.create
          value: "false"
        - name: serviceAccount.name
          value: "semanix-backend-accessmanagement"
        - name: image.repository
          value: samthedonz.azurecr.io/accessmanagementapi
        - name: image.tag
          value: latest
      values: |
        dapr:
          enabled: true
          appId: accessmanagement
          appPort: 8080
          config: dapr-config
  destination:
    server: https://kubernetes.default.svc
    namespace: semanix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
