apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semanix-backend-requestmanagement
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${AZURE_REGISTRY_NAME}.azurecr.io/helm
    targetRevision: 0.1.0
    chart: requestmanagement
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: serviceAccount.create
          value: "false"
        - name: serviceAccount.name
          value: "semanix-backend-requestmanagement"
      image:
             repository: samthedonz.azurecr.io/requestmanagementapi
             tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: semanix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true