name: AccessManagement Deployment

on:
  push:
    paths:
      - 'SemanixBackend/src/Services/AccessManagement/**'
      - 'deploy/helm/charts/accessmanagement/**'
      - 'deploy/k8s/argocd/accessmanagement-app.yaml'
    branches: [ main ]

jobs:
  deploy:
    uses: ./.github/workflows/microservice-cicd-template.yaml
    with:
      service_name: accessmanagement
      docker_context: ./SemanixBackend
      dockerfile_path: ./SemanixBackend/src/Services/AccessManagement/AccessManagement.Api/Dockerfile
      helm_chart_path: ./deploy/helm/charts/accessmanagement
      helm_chart_name: accessmanagement
      argocd_app_file: ./deploy/k8s/argocd/accessmanagement-app.yaml
    secrets: inherit
