name: AccessManagement CI

on:
  push:
    branches: [ main ]
    paths:
      - 'SemanixBackend/src/Services/AccessManagement/**'
      - '.github/workflows/accessmanagement-cicd.yaml'
      - '.github/workflows/microservice-ci-template.yaml'

jobs:
  build-and-push:
    uses: ./.github/workflows/microservice-ci-template.yaml
    with:
      service_name: 'accessmanagement'
      docker_context: 'SemanixBackend'
      dockerfile_path: 'SemanixBackend/src/Services/AccessManagement/AccessManagement.Api/Dockerfile'
    secrets:
      AZURE_REGISTRY_NAME: ${{ secrets.AZURE_REGISTRY_NAME }}
      AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
      AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
