name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: [self-hosted, azure]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore SemanixBackend/SemanixBackend.sln

    - name: Build
      run: dotnet build SemanixBackend/SemanixBackend.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test SemanixBackend/SemanixBackend.sln --configuration Release --no-build

    # - name: SonarQube Scan
    #   uses: SonarSource/sonarcloud-github-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   with:
    #     args: >
    #       -Dsonar.projectKey=semantixbackend
    #       -Dsonar.organization=semantixbackend

  build-and-push-docker:
    needs: build-and-test
    runs-on: [self-hosted, azure]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and push AccessManagement API
      uses: docker/build-push-action@v4
      with:
        context: ./SemanixBackend
        file: ./SemanixBackend/src/Services/AccessManagement/AccessManagement.Api/Dockerfile
        push: true
        tags: |
          ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/accessmanagementapi:latest

    - name: Build and push RequestManagement API
      uses: docker/build-push-action@v4
      with:
        context: ./SemanixBackend
        file: ./SemanixBackend/src/Services/RequestManagement/RequestManagement.Api/Dockerfile
        push: true
        tags: |
          ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/requestmanagementapi:latest

    - name: Scan Docker Images for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.REGISTRY_URL }}/accessmanagementapi:latest
        format: 'sarif'
        output: 'trivy-results.sarif'

  update-helm-charts:
    needs: build-and-push-docker
    runs-on: [self-hosted, azure]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3

    - name: Package Helm charts
      run: |
        helm package ./helm/charts/accessmanagement -d ./helm/releases
        helm package ./helm/charts/requestmanagement -d ./helm/releases
        az acr login --name ${{ secrets.AZURE_REGISTRY_NAME }}
        helm push ./helm/releases/accessmanagement-*.tgz oci://
        helm push ./helm/releases/requestmanagement-*.tgz oci://

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./deploy/helm/releases
        git commit -m "Update Helm charts" || echo "No changes to commit"
        git push 

  sync-argocd:
    needs: update-helm-charts
    runs-on: [self-hosted, azure]
    steps:
    - name: Install Argo CD CLI
      run: |
        curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd
        sudo mv argocd /usr/local/bin

    - name: Argo CD Login
      run: |
        argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USER }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

    - name: Sync Argo CD Application
      run: |
        argocd app sync semanix-backend
        argocd app wait semanix-backend --health --timeout 120s 