name: Continuous Integration

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better SonarQube analysis
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore SemanixBackend/SemanixBackend.sln
    
    - name: Build
      run: dotnet build SemanixBackend/SemanixBackend.sln --no-restore --configuration Release
    
    - name: Test
      run: dotnet test SemanixBackend/SemanixBackend.sln --no-build --verbosity normal
      
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=semanix_backend
          -Dsonar.organization=your-organization
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./SemanixBackend
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          your-registry/semanix-backend:latest
          your-registry/semanix-backend:${{ github.sha }}
        
    - name: Send Teams notification
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.TEAMS_WEBHOOK }}
        title: "Build Status"
        message: "Build for commit ${{ github.sha }} completed"
        theme_color: ${{ job.status == 'success' && '00FF00' || 'FF0000' }} 