name: Microservice CI Template

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      docker_context:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
    secrets:
      AZURE_REGISTRY_NAME:
        required: true
      AZURE_REGISTRY_USERNAME:
        required: true
      AZURE_REGISTRY_PASSWORD:
        required: true

jobs:
  build-and-push:
    runs-on: [self-hosted, azure]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set Docker tag (auto generate)
      id: set_docker_tag
      run: |
        COMMIT_COUNT=$(git rev-list --count HEAD)
        VERSION="0.2.8${COMMIT_COUNT}"
        echo "docker_tag=$VERSION" >> $GITHUB_OUTPUT
        echo "Using version: $VERSION"

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and Push Image
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.docker_context }}
        file: ${{ inputs.dockerfile_path }}
        push: true
        tags: |
          ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/${{ inputs.service_name }}api:${{ steps.set_docker_tag.outputs.docker_tag }}
          ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/${{ inputs.service_name }}api:latest
        build-args: |
          BUILD_CONFIGURATION=Release