name: RequestManagement CI

on:
  push:
    branches: [ ci ]
    paths:
      - 'SemanixBackend/src/Services/RequestManagement/**'
      - '.github/workflows/requestmanagement-cicd.yaml'
      - '.github/workflows/microservice-ci-template.yaml'

jobs:
  build-and-push:
    uses: ./.github/workflows/microservice-ci-template.yaml
    with:
      service_name: 'requestmanagement'
      docker_context: 'SemanixBackend'
      dockerfile_path: 'SemanixBackend/src/Services/RequestManagement/RequestManagement.Api/Dockerfile'
    secrets:
      AZURE_REGISTRY_NAME: ${{ secrets.AZURE_REGISTRY_NAME }}
      AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
      AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
